name: Daily Word Bot

on:
  schedule:
    - cron: "0 3 * * *"   # every day at 9:00 AM IST
  workflow_dispatch:       # manual trigger

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install

      - run: node sendWord.js
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH: ${{ secrets.TWILIO_AUTH }}
          TWILIO_FROM: ${{ secrets.TWILIO_FROM }}
          TWILIO_TO: ${{ secrets.TWILIO_TO }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
